#!/bin/sh
set -e
# notice the / at end in order to load this module
PACKAGE='constants-browserify'
SEDCMD="s,require\s*[(]\s*['\"][.]/?([^'\"]*)['\"]\s*[)],require('$PACKAGE/\1'),g"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT INT TERM HUP

cp test.js "$tmpdir/test.js"
echo 'test.js' | \
    xargs -n1  \
	  sh -c 'set -e; echo "Create: $3"; sed -E "$1" < "$3" > "$2/$3"' sedtape "$SEDCMD" "$tmpdir"
node "$tmpdir/test.js"
