#!/bin/sh

set -e

CONSTANTS_FILE="${DPKG_ROOT:-}/usr/share/nodejs/constants-browserify/constants.json"

case "$1" in
	remove)
		rm -f "$CONSTANTS_FILE"
		;;
	purge|upgrade|failed-upgrade|abort-upgrade|abort-install)
		;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac


#DEBHELPER#

exit 0
